baseURL = 'http://example.org/'
languageCode = 'sv-se'
title = 'Hampus safe space' 

theme = "paper"

# Optional but nice for minimal blogs
paginate = 10
enableRobotsTXT = true

[params]
  color = 'linen'                           # linen, wheat, gray, light
  color = 'auto'           # light, dark, or auto
  homeSubtitle = "Take a break in my safe space"
  github = 'hampusadamsson'   # Optional social links
  # rss = true

  bio = 'Software Engineer'

[menu]
  
  # [[menu.main]]
  #   name = "About"
  #   url = "/about/"
  #   weight = 2
  #
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

